site_name: "Orchestra Cities"
site_url: https://orchestracities.com
site_description: 'Orchestra Cities Documentation'
site_author: 'Martel Innovate'
copyright: 'Copyright &copy; 2020 - Martel Innovate'
theme: readthedocs
markdown_extensions: [toc,fenced_code]
docs_dir: docs
nav:
    - Home: 'index.md'
    - 'Introduction': 'introduction.md'
    - 'Security':
      - 'Auth Provider (Keycloak)': 'keycloak.md'
      - 'Api Management (Gravitee)': 'gravitee.md'
    - 'Tutorial': 'tutorial.md'
    - 'Build': 'build.md'
    - 'How to contribute': 'contribute.md'
