site_name: "Orchestra Cities"
site_url: https://orchestracities.com
site_description: 'Orchestra Cities Documentation'
site_author: 'Martel Innovate'
copyright: 'Copyright &copy; 2020 - Martel Innovate'
theme: readthedocs
markdown_extensions: [toc,fenced_code]
docs_dir: docs
nav:
    - Home: 'index.md'
    - '1. Platform overview': 'introduction.md'
    - '2. Architecture': 'architecture.md'
    - '3. Deploy an example instance': 'deploy.md'
    - '4. Security configuration':
      - '1. Auth Provider (Keycloak)': 'keycloak.md'
      - '2. Api Management (Gravitee)': 'gravitee.md'
      - '3. Admin Portal': 'portal.md'
    - '5. Tutorial': 'tutorial.md'
    - '6. How to contribute': 'contribute.md'
